### PR TITLE
do not try to resolve an already resolved path

### PR DESCRIPTION
**Pull request by aretecode**
side note: why are there so many empty lines in the code?

### CODE REVIEW

**Comment by neogeek** [comment]
This is great. Thanks! I'll take a look into why the tests are breaking after work.

As for the whitespace, I kinda go nuts with that stuff. I plan on normalizing it when I add prettier to all of my open source projects.

**Comment by aretecode** [comment]
@neogeek ok cool.

heh heh yeah prettier autofixed it nicely

**Comment by aretecode** [comment]
@neogeek ping

**Comment by neogeek** [comment]
Sorry for taking so long to get to this PR.

I've looked further into this issue and I'm not sure the code supplied will work. I've added new tests on master using absolute paths and I can not get them to work with your branch.

I've pushed a separate fix to master hopefully resolving any issues with using absolute paths. Can you confirm this is the case?

Thank you again for the PR and bringing this issue to my attention!

**Comment by aretecode** [comment]
@neogeek yeah I forgot to call promise resolve with the resolved paths :-P I'll check

**Comment by neogeek** [comment]
Shipped the fix for this issue in [v2.0.3](https://github.com/neogeek/doxdox/releases/tag/v2.0.3)

**Pull request closed without merging**
